// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPbIJ8e8lA1yL7IwDwinVZayTC4Ol53M',
    appId: '1:980482086441:web:32abefe7dd3826f9502e38',
    messagingSenderId: '980482086441',
    projectId: 'g2stock',
    authDomain: 'g2stock.firebaseapp.com',
    storageBucket: 'g2stock.appspot.com',
    measurementId: 'G-VQ4VQC1PSS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7ubmcYA2mc_LLcXqP2KniuGchsgSVXM',
    appId: '1:980482086441:ios:af0f33d4b35ce2c8502e38',
    messagingSenderId: '980482086441',
    projectId: 'g2stock',
    storageBucket: 'g2stock.appspot.com',
    iosBundleId: 'com.example.g2s',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUPbIJ8e8lA1yL7IwDwinVZayTC4Ol53M',
    appId: '1:980482086441:web:0d962d6f70d27d6d502e38',
    messagingSenderId: '980482086441',
    projectId: 'g2stock',
    authDomain: 'g2stock.firebaseapp.com',
    storageBucket: 'g2stock.appspot.com',
    measurementId: 'G-7QWPR08W1Y',
  );
}
